# Generated by Django 4.1.2 on 2022-10-31 12:54

from django.db import migrations, models
import django.db.models.deletion
import wep_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='cart_img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.BooleanField(default=False, help_text='0-Add, 1-Remove')),
                ('order_status', models.IntegerField(choices=[(1, 'new_order'), (2, 'old_order'), (0, 'not_order')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orderby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=30)),
                ('order_status', models.IntegerField(choices=[(1, 'success'), (2, 'pending'), (0, 'cancel')], default=2)),
                ('tax', models.IntegerField(default=wep_app.models.tax)),
                ('ordered_things', models.ManyToManyField(to='wep_app.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Pictures')),
                ('category', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.BooleanField(default=False, help_text='0-Show, 1-Hidden')),
                ('added', models.IntegerField(choices=[(1, 'added_wish'), (2, 'added_cart'), (0, 'not_added')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='cart_img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.BooleanField(default=False, help_text='0-Add, 1-Remove')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.prodect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('dist', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.orderby')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.prodect'),
        ),
    ]
