# Generated by Django 4.1.2 on 2022-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='tax',
            field=models.IntegerField(default=0.18),
        ),
    ]
