# Generated by Django 3.2.12 on 2022-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0002_alter_orderby_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'new_order'), (2, 'old_order'), (0, 'not_order')], default=0),
        ),
        migrations.AlterField(
            model_name='prodect',
            name='added',
            field=models.IntegerField(choices=[(1, 'added_wish'), (2, 'added_cart'), (0, 'not_added')], default=0),
        ),
    ]
