# Generated by Django 3.2.12 on 2022-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0003_auto_20221031_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='tax',
            field=models.FloatField(default=0.18),
        ),
    ]
