# Generated by Django 4.1.2 on 2022-11-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0004_alter_orderby_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'new order'), (2, 'old order'), (0, 'not order'), (3, 'cancel order')], default=0),
        ),
        migrations.CreateModel(
            name='MyInlineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wep_app.wishlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
