# Generated by Django 4.1.2 on 2022-11-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wep_app', '0005_alter_cart_order_status_myinlinemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyInlineModel',
        ),
    ]
